// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8tX-YyqPisQdc-JbxEhOgIfthSQC5dE',
    appId: '1:756002918244:web:0d38ea396aa2dab9523471',
    messagingSenderId: '756002918244',
    projectId: 'travaling-1a1ab',
    authDomain: 'travaling-1a1ab.firebaseapp.com',
    storageBucket: 'travaling-1a1ab.appspot.com',
    measurementId: 'G-NNDF5D8717',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClASe7rC6UEuiwzbe2de8qnL12fDYTtdU',
    appId: '1:756002918244:android:d33eb126a0ff79bd523471',
    messagingSenderId: '756002918244',
    projectId: 'travaling-1a1ab',
    storageBucket: 'travaling-1a1ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzQmFgLo-HERNF36Fe0yD8x-ceczc1JE',
    appId: '1:756002918244:ios:f9b192bebb8af1a8523471',
    messagingSenderId: '756002918244',
    projectId: 'travaling-1a1ab',
    storageBucket: 'travaling-1a1ab.appspot.com',
    iosClientId: '756002918244-m9sqatc97dfqaf5mjckqibknq5ks3gf7.apps.googleusercontent.com',
    iosBundleId: 'com.traveling.travelingAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzQmFgLo-HERNF36Fe0yD8x-ceczc1JE',
    appId: '1:756002918244:ios:121539d65158136b523471',
    messagingSenderId: '756002918244',
    projectId: 'travaling-1a1ab',
    storageBucket: 'travaling-1a1ab.appspot.com',
    iosClientId: '756002918244-39prkbbbo77r7l5ecsjajlifjv68ad3a.apps.googleusercontent.com',
    iosBundleId: 'com.traveling.travelingAppFlutter.RunnerTests',
  );
}
